global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']
          # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  - "alert_rules.yml"
  # - "first_rules.yml"
  # - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'
    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.
    metrics_path: "/metrics"
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node'
    static_configs:
      - targets: [ 'node-exporter:9100' ]

  - job_name: 'alertmanager'
    static_configs:
      - targets: [ 'alertmanager:9093' ]

  - job_name: 'PromotionPlanning'
    scrape_interval: 5s
    scrape_timeout: 5s
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ['host.docker.internal:8080']
        labels:
          instance: demo-app

  - job_name: 'kubernetes-apiservers'
    scrape_interval: 5s
    scrape_timeout: 5s
    metrics_path: "/actuator/prometheus"
    kubernetes_sd_configs:
      - api_server: https://api.cic-rgm-dev-us21.rgm.shoot.live.k8s-hana.ondemand.com
#      - api_server: https://kubernetes.docker.internal:6443
#        bearer_token: eyJhbGciOiJSUzI1NiIsImtpZCI6IlBmZExvdFlleTZwZ2VscXAyRWxaQzZCNkRGT2RrS2RVb1F6b0ppQ3N0bU0ifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJkZWZhdWx0Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZWNyZXQubmFtZSI6InByb21ldGhldXMiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC5uYW1lIjoicHJvbWV0aGV1cyIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50LnVpZCI6Ijk2NjllOGUyLTk0YTktNDZjNi1hODVhLWUwZDczNjFjZDg0NiIsInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDpkZWZhdWx0OnByb21ldGhldXMifQ.X785U79XIy43e1bg9bBsFOchPjftzdAOB4fWs4FGFdEFg17IY-yQa3wMcQM310EXoTZajmmW2MOn7wtHwTWurle1lAoq4jVxktblNl9TAk2wpmophYCjfIjtbe-QQbVaGjh-5XPR8sdazF1NjbREP4btlC7E1ni7XykCxEIY3XTnC_womsMhBQKtv0jcmWOOrHPwFtqU481aX3BPdjJgmeVh49G-Vf8l8UdsAtsklczDtdWnpzADjTtoNHzQJ2hvs_1z4l93MOrsh0AJA2H9XX_ucp4sxywYv2-4IY-UTFwa1OVpK4pAW7ziv0d1LMYPpBvXo4oV8pn7PEeI6dRxRg
        bearer_token: eyJhbGciOiJSUzI1NiIsImtpZCI6Ino3RG8yWS12MFFZQ0pVcUxUR3RJeTBzM0FnYkNxT3Y2NHFiVmFKWGxjT0UifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJkZWZhdWx0Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZWNyZXQubmFtZSI6InByb21ldGhldXMiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC5uYW1lIjoicHJvbWV0aGV1cyIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50LnVpZCI6ImMyOTYxYTkxLTAyNGUtNDQwYS1hZmIyLTg2MTk5ZGJiNWExYSIsInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDpkZWZhdWx0OnByb21ldGhldXMifQ.G2obBbiWKU1U7Q0UF2ylcQiT11J1TI6wP3ejbvy5lqoa4QvBayDht5oL-_EoMqACb4hDMv3xsUnuKBZEsjV6BjRnCwo7BaOkVuhC75MbAtnrac7T7cbIxMFsbJD1iAfHvs8CS1ase-eWSYcjxs_Vm69Hn7c8zAXCPNG_7QxfBe5mendld3-alHxJ7si7P8yVlJZWf0tZtqQFlL4w1A_zq8BmMy0glotsYQGWWNHj0iCe3yzxmj5Bpfgiib3dbz4TNSn2V1rjKmnRum7gtewKpGP-isxtTQmh8B6oEmSJSvhv-Lb1--m8wv2vUykYAKUc1eOhesZZX6wNyKs54L04HvbNk1ROB9s1URxCW-E8pBA1kWNDN9G4hm829VP7fJZXcc-YElYt9Xm7GRjDrzypo2Ly-TMcnGMp7Tyf-6kNvMKm9LUS5Re6k3Xv2w7ZAF50F7aSEFRw1JDY8cgJ_pFJ_9browW7sV9jZzIGdf6VJ9xZ7mS2o3WBFLize92t0jSD4nFfUE96xVtA7ttOPUwcIud7i86_bsriZBjVdYH1CJuvYG5UHzWuaxM4rGLNSnsXjSSTDwNVa1KyFY0I0icyOCEQfbkd3V1ib2YylzSIdcUTVLuYOGrQadrH55GDOb6aQiYtlFdhSFz8XUbtTYE-x3o2nWBDDJl00Vqs8yxRE98
        role: endpoints
        namespaces:
          names:
            - rgm-dev
        tls_config:
          insecure_skip_verify: true
    tls_config:
      insecure_skip_verify: true
    relabel_configs:
      - source_labels: [__meta_kubernetes_namespace,__meta_kubernetes_service_name]
        action: keep
        regex: rgm-dev;rgp-promotion-planning
