version: '3'
services:
  postgres:
    image: postgres:12-alpine
    environment:
      - POSTGRES_PASSWORD=Initial0
    volumes:
      - mypg1:/var/lib/postgresql/data
    ports:
      - 5433:5432

  postgres2:
    image: postgres:12-alpine
    environment:
      - POSTGRES_PASSWORD=Initial0
    volumes:
      - mypg2:/var/lib/postgresql/data
    ports:
      - 5434:5432

  pgadmin:
    image: dpage/pgadmin4:4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@sap.com
      - PGADMIN_DEFAULT_PASSWORD=Initial0
    ports:
      - 18000:80
    links:
      - postgres:postgres
      - postgres2:postgres2

volumes:
  mypg1:
  mypg2:


