#server.port=18080
server.tomcat.max-connections=8192
server.tomcat.threads.max=800
server.tomcat.threads.min-spare=10
server.tomcat.accept-count=100

management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

spring.boot.admin.client.url=http://127.0.0.1:8080
