#################################### SMTP / Emailing ##########################
# 配置邮件服务器
[smtp]
enabled = true
# 发件服务器
host = smtp.163.com:465
# smtp账号
user = cslgduke@163.com
# smtp 授权码
password = JLXLUKPYWLCUZWVQ
# 发信邮箱
from_address = cslgduke@163.com
# 发信人
from_name = dave
