version: '3'
services:
#  demo-app-openjdk:
#    image: demo-app:openjdk
#    ports:
#      - 18081:18081


#  demo-app-17-jre-headless-ubuntu:
#    image: demo-app:17-jre-headless-ubuntu
#    ports:
#      - 18081:18081

#  demo-app-distroless:
#    image: demo-app:distroless
#    ports:
#      - 18081:18081

  postgres:
    image: postgres:12-alpine
    environment:
      - POSTGRES_PASSWORD=Initial0
    volumes:
      - mypg1:/var/lib/postgresql/data
    ports:
      - 5433:5432

  postgres2:
    image: postgres:12-alpine
    environment:
      - POSTGRES_PASSWORD=Initial0
    volumes:
      - mypg2:/var/lib/postgresql/data
    ports:
      - 5434:5432


  redis:
    image: redis:6.0
    command: redis-server --requirepass default
    ports:
      - 16379:6379

volumes:
  mypg1:
  mypg2: