apiVersion: v1
kind: ConfigMap
metadata:
  name: Dockerfile-storage
data:
  dockerfile: |
    FROM alpine:latest
    RUN echo "this is a customized dockerfile"
---
apiVersion: v1
kind: Pod
metadata:
  name: alpine-test
spec:
  volumes:
    - name: Dockerfile-storage
      configMap:
        name: Dockerfile-storage
  containers:
    - name: alpine-test
      image: alpine:latest
#      command: [ "/bin/sh", "-c", "cat /workspace/Dockerfile", "env" ]
      command:
        - /bin/sh
        - -c
        - |
          echo "this is a customized dockerfile"
          cat /workspace/dockerfile
          echo "this is the third command"
      volumeMounts:
        - name: Dockerfile-storage
          mountPath: /workspace
  restartPolicy: Never
