apiVersion: v1
kind: ConfigMap
metadata:
  name: Dockerfile-storage
data:
  dockerfile: |
    FROM alpine:latest
    RUN echo "create from standard input!"
---
apiVersion: v1
kind: Pod
metadata:
  name: kaniko
spec:
  containers:
    - name: kaniko
      image: gcr.io/kaniko-project/executor:latest
      args: ["--Dockerfile=/workspace/Dockerfile",
             "--context=dir://workspace",
            # "--no-push",
             "--destination=cslgduke/demo"] # replace with your dockerhub account
      volumeMounts:
        - name: kaniko-secret
          mountPath: /kaniko/.docker
        - name: Dockerfile-storage
          mountPath: /workspace
  restartPolicy: Never
  volumes:
    - name: kaniko-secret
      secret:
        secretName: regcred
        items:
          - key: .dockerconfigjson
            path: config.json
    - name: Dockerfile-storage
      configMap:
        name: Dockerfile-storage
#kubectl create secret docker-registry regcred --docker-username=cslgduke --docker-password=330879214DUke --docker-email=cslgduke@163.com