apiVersion: services.cloud.sap.com/v1
kind: ServiceInstance
metadata:
  name: rgm-dev-dpi-ng-retention
spec:
  serviceOfferingName: data-privacy-integration-service
  servicePlanName: data-privacy-internal
  parameters:
    xs-security:
      xsappname: rgm-dev-dpi-ng-retention
      authorities:
        - "$ACCEPT_GRANTED_AUTHORITIES"
      oauth2-configuration:
        credential-types:
          - x509
          - binding-secret
    dataPrivacyConfiguration:
      configType: retention
      applicationConfiguration:
        applicationName: SAP-RGM
        applicationDescription: SAP Revenue Growth Management
      retentionConfiguration:
        applicationConfiguration:
          applicationType: TransactionMaster
          simulationSupportedForArchiving: true
          simulationSupportedForDestruction: true
        dataSubjectRoles:
          - dataSubjectRoleName: RgmUser
            dataSubjectDescription: RgmUser
            dataSubjectBaseURL: https://api.rgm-dev.rgm-cic-rgm-dev-us21.eurekacloud.io
            dataSubjectBlockingEndPoint: "/drm-ng/dataSubjectBlocking"
        organizationAttributes:
          - organizationAttributeName: RGM
            organizationAttributeDescription: Revenue Growth Management
            organizationAttributeBaseURL: https://api.rgm-dev.rgm-cic-rgm-dev-us21.eurekacloud.io
            organizationAttributeValueHelpEndPoint: "/drm-ng/organizationAttributeValueHelp"
        iLMObjects:
          - iLMObjectName: RgmUser
            iLMObjectType: Transaction
            iLMObjectDescription: RgmUser
            iLMObjectBaseURL: https://api.rgm-dev.rgm-cic-rgm-dev-us21.eurekacloud.io
            organizationAttributeName: RGM
            referenceDates:
              - referenceDateName: create_time
                referenceDateDescription: create_time
              - referenceDateName: update_time
                referenceDateDescription: update_time
            dataSubjectBlockingConfiguration:
              dataSubjectEndOfBusinessEndPoint: "/drm-ng/dataSubjectEndOfBusiness"
              dataSubjectOrganizationAttributesEndPoint: "/drm-ng/dataSubjectOrganizationAttributes"
              dataSubjectLastRetentionStartDatesEndPoint: "/drm-ng/dataSubjectLastRetentionStartDates"
              dataSubjectsEndOfResidenceEndPoint: "/drm-ng/dataSubjectsEndOfResidence"
              dataSubjectsEndOfResidenceConfirmationEndPoint: ''
              dataSubjectILMObjectBlockingEndPoint: "/drm-ng/dataSubjectILMObjectBlocking"
              dataSubjectsILMObjectDestroyingEndPoint: "/drm-ng/dataSubjectsILMObjectDestroying"
            dataSubjectRoles:
              - dataSubjectRoleName: RgmUser
---
apiVersion: services.cloud.sap.com/v1
kind: ServiceBinding
metadata:
  name: rgm-dev-dpi-ng-retention
spec:
  serviceInstanceName: rgm-dev-dpi-ng-retention
  secretName: rgm-dev-dpi-ng-retention