server.port=18081
spring.application.name=admin-client

#hikari
spring.datasource.hikari.maximum-pool-size=20
spring.datasource.hikari.minimum-idle=20
#spring.datasource.hikari.idle-timeout=0
#spring.datasource.hikari.leak-detection-threshold=5000

#hikaricp.admin.enabled=true
#hikaricp.admin.dashboard.enabled=true
#hikaricp.admin.healthcheck.enabled=true
#hikaricp.admin.healthcheck.interval=10000

#jpa
#spring.jpa.properties.hibernate.generate_statistics=true
spring.jpa.properties.hibernate.jdbc.batch_size=1000
spring.jpa.properties.hibernate.order_inserts=true
#spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
#spring.jpa.hibernate.ddl-auto=none

#Mysql
#spring.datasource.url=jdbc:mysql://localhost:3306/demo?allowPublicKeyRetrieval=true&useSSL=false
#spring.datasource.username=root
#spring.datasource.password=password
#spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL5Dialect



#PG
#spring.datasource.url=jdbc:postgresql://localhost:5433/postgres
#spring.datasource.username=postgres
#spring.datasource.password=Initial0
#spring.datasource.driverClassName=org.postgresql.Driver

#disaggregtaion
#spring.datasource.url=jdbc:sap://cf47da9b-878d-40f0-b4bf-58c2bbabba89.hana.prod-us21.hanacloud.ondemand.com:443?encrypt=true&validateCertificate=false&currentschema=RGM_DISAGGREGATION_DATA__07F472B5__229812828508160&reconnect=true
#spring.datasource.username=RGM_DISAGGREGATION_DATA__07F472B5__229812828508160__SERVICE_USER
#spring.datasource.password=SK3r9CIgdI5Iq8i2dT3l
#spring.datasource.driverClassName=com.sap.db.jdbc.Driver

#local
spring.datasource.url=jdbc:sap://6f758b58-e46f-4b2a-aedd-c4ce75c67f0a.hana.prod-cn40.hanacloud.sapcloud.cn:443?encrypt=true&validateCertificate=false&currentschema=DISAG_DATA_TEST_I565244&reconnect=true
spring.datasource.username=DISAG_DATA_TEST_i565244
spring.datasource.password=Initial0
spring.datasource.driverClassName=com.sap.db.jdbc.Driver
spring.datasource.hikari.idle-timeout=0

#kpi
#spring.datasource.url=jdbc:sap://cf47da9b-878d-40f0-b4bf-58c2bbabba89.hana.prod-us21.hanacloud.ondemand.com:443?encrypt=true&validateCertificate=false&currentschema=RGM_KPI_SERVICE__F9A0B723__229812828508160&reconnect=true
#spring.datasource.username=RGM_KPI_SERVICE__F9A0B723__229812828508160__SERVICE_USER
#spring.datasource.password=4YKh233KFz0Qso9rJyVe
#spring.datasource.driverClassName=com.sap.db.jdbc.Driver
#spring.datasource.hikari.maximum-pool-size=100
#spring.datasource.hikari.minimum-idle=100
#spring.datasource.hikari.transactionIsolation=TRANSACTION_READ_UNCOMMITTED

#druid
#spring.datasource.druid.initial-size= 5
#spring.datasource.druid.min-idle= 100
#spring.datasource.druid.test-while-idle=false
#spring.datasource.druid.max-active= 100
#spring.datasource.druid.stat.slow-sql-millis=1000
#spring.datasource.druid.web-stat-filter.enabled=true
#spring.datasource.druid.stat-view-servlet.enabled= true
#spring.datasource.druid.stat-view-servlet.url-pattern= /druid/*
#spring.datasource.druid.filter.stat.log-slow-sql=true
#spring.datasource.druid.filter.stat.slow-sql-millis=1000
#spring.datasource.type=com.alibaba.druid.pool.DruidDataSource




#spring.datasource.primary.url=jdbc:postgresql://localhost:5433/postgres
#spring.datasource.primary.username=postgres
#spring.datasource.primary.password=Initial0
#spring.datasource.primary.driverClassName=org.postgresql.Driver
#
#spring.datasource.secondary.url=jdbc:mysql://localhost:3306/test2
#spring.datasource.secondary.username=postgres
#spring.datasource.secondary.password=Initial0
#spring.datasource.secondary.driverClassName=org.postgresql.Driver



server.tomcat.max-connections=8192
server.tomcat.threads.max=200
server.tomcat.threads.min-spare=10
server.tomcat.accept-count=100

spring.liquibase.change-log=classpath:db/master.xml
spring.liquibase.enabled=false
spring.liquibase.drop-first=false
#spring.liquibase.contexts=application


#endpoint
management.endpoints.web.exposure.include=*
#management.endpoints.web.exposure.include=info,liquibase,health,metrics,prometheus,loggers
#health
management.endpoint.health.show-details=always

management.metrics.export.prometheus.enabled=true
management.metrics.export.prometheus.step=1m
management.metrics.export.prometheus.port=8081

#management.endpoint.prometheus.cache.time-to-live = 0ms
#management.prometheus.metrics.export.enabled=true
#management.endpoint.metrics.tags.application=demo-app(dave)
#management.endpoint.metrics.tags.region=my-region




# signBits + timestampBits + workerIdBits + sequenceBits = 64
#uid.time-bits=28
#uid.worker-bits=22
#uid.seq-bits=13

#uid.time-bits=38
#uid.worker-bits=15
#uid.seq-bits=10

#uid.time-bits=48
#uid.worker-bits=10
#uid.seq-bits=5

uid.time-bits=59
uid.worker-bits=2
uid.seq-bits=2


#########kafka############
#spring.kafka.bootstrap-servers=pkc-epwny.eastus.azure.confluent.cloud:9092
spring.kafka.bootstrap-servers= 127.0.0.1:9092
spring.kafka.producer.sasl.jaas.config= org.apache.kafka.common.security.plain.PlainLoginModule required username="kafka" password="kafka_secret";
spring.kafka.producer.sasl.mechanism= PLAIN
spring.kafka.producer.security.protocol=PLAINTEXT
#########producer
#spring.kafka.producer.retries=2
#spring.kafka.producer.retry.backoff.ms= 1000
#spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
#spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer
#spring.kafka.producer.batch-size=1
#spring.kafka.producer.linger-ms=1
#spring.kafka.producer.buffer-memory=33554432
#########listener
#spring.kafka.listener.concurrency=5
#spring.kafka.listener.ack-mode=manual_immediate

eureka.framework.kafka.producer.request.timeout.ms = 1000
eureka.framework.kafka.producer.max.block.ms = 2000



#spring.cache.type=CAFFEINE
## expired 12*60*60 = 43200s
#spring.cache.caffeine.spec=maximumSize=500,expireAfterAccess=43200s
#spring.cache.cacheNames=userCache,demoCache

spring.redis.host=localhost
spring.redis.port=16379
spring.redis.password=default
spring.redis.timeout=30000

spring.boot.admin.client.url=http://127.0.0.1:8080
#logging.file.name=admin-client.log
