apiVersion: services.cloud.sap.com/v1alpha1
kind: ServiceInstance
metadata:
  name: rgm-sit-dpi
spec:
  serviceOfferingName: data-privacy-integration-service
  servicePlanName: application
  parameters:
    xs-security:
      xsappname: rgm-sit-rgp
      authorities:
        - "$ACCEPT_GRANTED_AUTHORITIES"
      oauth2-configuration:
        credential-types:
          - x509
          - binding-secret
    dppConfig:
      applicationName: rgm-dpi-rgm-sit
      information:
        fullyQualifiedApplicationName: rgp-dpi-proxy
        applicationTitle: SAP Revenue Growth Planning
        applicationTitleKey: rgp-dpi-proxy
        cacheControl: "no-cache"
        dataSubjectDeletionUri: https://api-rgm-sit.rgm-cic-rgm-dev-us21.eurekacloud.io/biz/v1/version/echo
        modules:
          - fullyQualifiedModuleName: rgp-dpi-proxy
            applicationURL: https://api-rgm-sit.rgm-cic-rgm-dev-us21.eurekacloud.io
            endPoints:
              - type: odataV4
                serviceName: rgp-dpp-proxy
                serviceTitle: rgp-dpp-proxy
                serviceTitleKey: rgp-dpp-proxy
                serviceURI: "/biz/v1/pdm/odata"
                hasGdprV4Annotations: true
      deletion:
        applicationGroupName: rgp-dpi-rgm-sit
        applicationGroupDescription: Revenue Growth Planning
        applicationGroupDescriptionKey: RGP
        applicationGroupBaseURL: https://api-rgm-sit.rgm-cic-rgm-dev-us21.eurekacloud.io
        dataSubjects:
          - dataSubjectRole: WorkforcePerson
            dataSubjectDescription: WorkforcePerson
            dataSubjectDescriptionKey: WorkforcePerson
            dataSubjectBaseURL: https://api-rgm-sit.rgm-cic-rgm-dev-us21.eurekacloud.io
            dataSubjectDeletionEndPoint: "/drm/dataSubjectDeletion"
            dataSubjectsDestroyingEndPoint: "/drm/dataSubjectsDestroying"
            legalEntity:
              legalEntity: RGP_Tenant
              legalEntityDescription: Revenue Growth Planning
              legalEntityDescriptionKey: RGP_Tenant
              legalEntityValueHelpEndPoint: "/drm/legalEntityValueHelp"
            legalGroundDiscovery: true
            legalGroundDiscoveryEndPoint: "/drm/legalGroundDiscovery"
